import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import AuthProvider from "./provider/provider";
import NavbarWrapper from "./(components)/shered/NavbarWrapper";
import LeftSideBarWrapper from "./(components)/shered/leftSideBar/LeftSideBarWrapper";
import Container from "./(components)/shered/Container";
import RightSideWrapper from "./(components)/shered/rightSideBar/RightSideWrapper";
import QueryProvider from "./provider/query-provider";

// import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`!bg-[#f3f4f6] ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AuthProvider>
      <QueryProvider>
      <NavbarWrapper></NavbarWrapper>
         <Container className="flex mt-4 flex-row gap-4">
         <LeftSideBarWrapper></LeftSideBarWrapper>
         <div className="w-full">
         <main>{children}</main>
         </div>
         <RightSideWrapper></RightSideWrapper>
         </Container>
          <ToastContainer />
      </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

